### PR TITLE
Blos 279 feat switch

### PR DESCRIPTION
**Pull request by realdreamer**
Preview: https://static-staging.usabilla.com/stylabilla/pr/blos-279-feat-switch/docs/section-components.html#kssref-components-switches

## What to test? Scope of the test?

- New `switch` toggle component

## Reviews

Reviewers: @usabilla/fe-chapter @galagmon @IreneFalgueras 

Required: 1 FE approval - 1 UI approval

## Checklist minimal
- [x] Export the component by importing it in the index.scss
- [x] Components are navigable by keyboard only
- [x] [Accessibility (ARIA attributes)](https://w3c.github.io/using-aria/) are included
- [x] Semantic HTML is used
- [ ] The component works across all device widths, and is built mobile first.
- [ ] Example for each modifier with description
- [ ] Example for each component with description

## Browsers compatibility checklist
These browsers were manually tested:
- [x] Chrome last version
- [x] Firefox last version
- [ ] Edge last version
- [x] IE11
- [x] Safari 10+
- [ ] IE9 - IE10 - Only if your element can be part of a public feedback form

### CODE REVIEW

**Comment by IreneFalgueras** [comment]
There seems to be a shadow inside the toggle, could it be removed?
 Please heck the attachments for reference. 
On Stylabilla
Screenshot 2019-08-14 at 16 40 13

On InVision
Screenshot 2019-08-14 at 16 40 18

**Comment by galagmon** [comment]
One question @realdreamer do we need different sizes? In the form filter, it is smaller than the implementation in stylabilla.
The one in Stylabilla still makes sense as the default 23px 
but we should have a S (16px) for this one

**Comment by realdreamer** [comment]
@galagmon Updated with small size variant

**Comment by realdreamer** [comment]
@galagmon - I'm merging this pr for now. Once you're back, if we need to do any fine tunings will do it as a separate fix.

**Pull request merged**
