### PR TITLE
feat(alert): add alert component

### PR DESCRIPTION
**Pull request by dine**
Related to https://github.com/usabilla/usabilla.js/pull/1447/files#r173720685

screen shot 2018-03-12 at 16 08 51

### CODE REVIEW

**Comment by galagmon** [comment]
Hi, which banner is that? where is the styling from?

**Comment by dine** [comment]
Yes, I was discussing with @gsbkr, he added the designs to the sketch file recently, that's why @galagmon have not seen it yet (I showed it to her now)

**Comment by gsbkr** [comment]
@dine you didn't add the 2px border radius yet. I assume these are the yellow-4 (#FFE1BE) for the fill and the yellow-2 (#FFD99C) for the border we discussed?

**Comment by dine** [comment]
@gsbkr added border radius. The colors are like in sketch, yellow-4 is #ffe1be and yellow-2 is #ffb867, you can check them on [stylabilla documentation](https://static-staging.usabilla.com/stylabilla/docs/section-style.html#kssref-style-colors-yellow)

**Pull request merged**
